version: '3.8'

volumes:
  postgres_volume:

services:
  db:
    image: postgres:16.1-alpine3.19
    environment:
      - "POSTGRES_DB=service-db"
      - "POSTGRES_USER=service-user"
      - "POSTGRES_PASSWORD=service-password"
    ports:
      - "54321:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data